### ISSUE TITLE
field for detail-page in plugin flexform

### ISSUE THREAD

**Issue by mxsteini** [cyperfection/cyz_address#1]
It would be great if you can implement a field for the detail-page in the plugin flexform.

**Comment by cyperfection** [comment]
Could you please specify what aspect of the detail page should be configurable via flexform or rather what that flexform field should do?

**Comment by mxsteini** [comment]
By now the detail-view is on the same page as the listview. 
But if I want a small list of addresses on my start-page (e. g. as teaser in the margin column), the detailview must be on another page.
