### ISSUE TITLE
addresses blow footer of page

### ISSUE THREAD

**Issue by averlon** [cyperfection/cyz_address#7]
Hi,
sorry, I have to correct me: the standard template works - so it must be somewhere in my own fluid definitions. I will check.
So please close issue.
Thanks
Karl-Heinz

Hi,
first of all, cyz_address is very much helpful to make use of tt_address with more extended tempaltes.

I have managed to get cyt_address working.
But now I am facing a problem.

T3 = 8.7.10
tt_address = 3.2.2
cyz_address = 0.5.0

I am using cyz with categories.

I have the following categries levels in my website:
- category = categories root
- - cat 1 on level 1
- - - cat 1.1 on level 2
- - - cat 1.2 on level 2
- - - - cat 1.2.1 on level 3
- - - - cat 1.2.2 on level 3
- - cat 2 on level 1

If I select "cat 1.2 on level 2" to be shown everything works fine.
All addresses are shown in the correct position according to the template, colpos, ...

If I select "cat 1.2.1 on level 3" the addresses are selected correct - but - all addresses are shown below (!!below!!) the page footer.

All other content which I have on this page is shown correct.

My implementation is based on the "Introduction Package".

I have tested back and forth using the standard template and my own - but always this result - only if categories below level 2 are selected.

Could you please check this or give me a hint what to do different to get this working!
Thanks
Karl-Heinz
You may check:
http://www.averlon.de/av_homep_80/index.php?id=63&L=0
http://www.averlon.de/av_homep_80/index.php?id=78&L=0

**Comment by averlon** [comment]
I will check my fluid definitions.

**Comment by averlon** [comment]
sorry, I have to reopen the issue.
It shows:
If I select only one of the categories on level 3 the site is in wrong order.
If I select all categories in level 3 the site is correct.

**Comment by cyperfection** [comment]
It seems that you copied the default template/partial and missed some of the closing tags or screwed up the closing order or something like that. This is not a problem related to cyz_address at all, it's propably your own fault.

Regardless, your HTML looks like this: 
`<table><tr><td><ul><li><table>...</table></div></li></ul></td></div>`
As you can see, your elements are not being closed properly and some closing tags are missing entirely.

By fixing this, I managed to have your page display properly.

**Comment by averlon** [comment]
Hi Luca,
yes, I know.
On the other hand, I only use one template and this works fine if all categories are selected.

You can see it in attached.
[List.txt](https://github.com/cyperfection/cyz_address/files/1775597/List.txt)

Thanks for help anyway.
Karl-Heinz
